export const SALE_LIST_REQUEST = 'SALE_LIST_REQUEST';
export const SALE_LIST_SUCCESS = 'SALE_LIST_SUCCESS';
export const SALE_LIST_FAIL = 'SALE_LIST_FAIL';

export const SALE_DETAILS_REQUEST = 'SALE_DETAILS_REQUEST';
export const SALE_DETAILS_SUCCESS = 'SALE_DETAILS_SUCCESS';
export const SALE_DETAILS_FAIL = 'SALE_DETAILS_FAIL';

export const SALE_CREATE_REQUEST = 'SALE_CREATE_REQUEST';
export const SALE_CREATE_SUCCESS = 'SALE_CREATE_SUCCESS';
export const SALE_CREATE_FAIL = 'SALE_CREATE_FAIL';
